import os
current_working_directory = os.getcwd()

DCPlanData_table = """CREATE TABLE DCPlanData(
	dcplanid varchar(50) NOT NULL,
	state varchar(50) NOT NULL,
	planname varchar(200) NOT NULL,
	fy int NOT NULL,
	year_est varchar(50) NULL,
	ppd_id text NULL,
	planname_db varchar(50) NULL,
    primary_ varchar(50) NOT NULL,
	cashbalance varchar(50) NOT NULL,
	hybrid varchar(50) NULL,
	mandatory_default varchar(50) NULL,
	plantype varchar(50) NULL,
	eligible_eegroups varchar(500) NOT NULL,
	actives varchar(50) NULL,
	inactives varchar(50) NOT NULL,
	members_total varchar(50) NULL,
	assets varchar(50) NULL,
	investmentoptions varchar(5) NULL,
	eq_avg float NOT NULL,
	ee_contrate_mandatory varchar(50) NULL,
	ee_contrate_max float NULL,
	ee_contrate_verbatim varchar(250) NULL,
	er_contrate_matchrate float NULL,
	er_contrate_fixedrate float NULL,
	er_contrate_verbatim varchar(500) NULL,
	conts_ee float NULL,
	conts_er float NULL,
	coveredpayroll float NOT NULL
)"""

PensionCreditRating_table = """CREATE TABLE PensionCreditRating(
	ppd_id float NULL,
	PlanName varchar(255) NULL,
	fy float NULL,
	RatingAgency varchar(255) NULL,
	Tot_MktValue_SP decimal(18, 2) NULL,
	Tot_ParValue_SP decimal(18, 2) NULL,
	Tot_MktValue_M float NULL,
	Tot_ParValue_M float NULL,
	Aaa_MktVal_M float NULL,
	Aaa_ParVal_M float NULL,
	Aa_MktVal_M float NULL,
	Aa_ParVal_M float NULL,
	A_MktVal_M float NULL,
	A_ParVal_M float NULL,
	Baa_MktVal_M float NULL,
	Baa_ParVal_M float NULL,
	Ba_MktVal_M float NULL,
	Ba_ParVal_M float NULL,
	B_MktVal_M float NULL,
	B_ParVal_M float NULL,
	CaaAndBelow_MktVal_M float NULL,
	CaaAndBelow_ParVal_M float NULL,
	Unrated_MktVal_M float NULL,
	Unrated_ParVal_M float NULL,
	BaAndBelow_MktVal_M decimal(18, 2) NULL,
	BaAndBelow_ParVal_M decimal(18, 2) NULL,
	AGY_MktVal_M decimal(18, 2) NULL,
	AGY_ParVal_M decimal(18, 2) NULL,
	P1_MktVal_M float NULL,
	P1_ParVal_M float NULL,
	P2_MktVal_M float NULL,
	P2_ParVal_M float NULL,
	GovGnteed_MktVal_M float NULL,
	GovGnteed_ParVal_M float NULL,
	Aaa_GovBond_MktVal_M decimal(18, 2) NULL,
	Aaa_GovBond_ParVal_M decimal(18, 2) NULL,
	Aa_GovBond_MktVal_M decimal(18, 2) NULL,
	Aa_GovBond_ParVal_M decimal(18, 2) NULL,
	A_GovBond_MktVal_M decimal(18, 2) NULL,
	A_GovBond_ParVal_M decimal(18, 2) NULL,
	Baa_GovBond_MktVal_M decimal(18, 2) NULL,
	Baa_GovBond_ParVal_M decimal(18, 2) NULL,
	Ba_GovBond_MktVal_M decimal(18, 2) NULL,
	Ba_GovBond_ParVal_M decimal(18, 2) NULL,
	B_GovBond_MktVal_M decimal(18, 2) NULL,
	B_GovBond_ParVal_M decimal(18, 2) NULL,
	CaaBelow_GovBond_MktVal_M decimal(18, 2) NULL,
	CaaBelow_GovBond_ParVal_M decimal(18, 2) NULL,
	Unrated_GovBond_MktVal_M decimal(18, 2) NULL,
	Unrated_GovBond_ParVal_M decimal(18, 2) NULL,
	Aaa_AgCMO_MktVal_M decimal(18, 2) NULL,
	Aaa_AgCMO_ParVal_M decimal(18, 2) NULL,
	Aaa_AgDebent_MktVal_M varchar(255) NULL,
	Aaa_AgDebent_ParVal_M varchar(255) NULL,
	Aaa_AgPool_MktVal_M decimal(18, 2) NULL,
	Aaa_AgPool_ParVal_M decimal(18, 2) NULL,
	Unrated_AgPool_MktVal_M decimal(18, 2) NULL,
	Unrated_AgPool_ParVal_M decimal(18, 2) NULL,
	Aaa_CMO_MktVal_M decimal(18, 2) NULL,
	Aaa_CMO_ParVal_M decimal(18, 2) NULL,
	Aa_CMO_MktVal_M decimal(18, 2) NULL,
	Aa_CMO_ParVal_M decimal(18, 2) NULL,
	A_CMO_MktVal_M decimal(18, 2) NULL,
	A_CMO_ParVal_M decimal(18, 2) NULL,
	Baa_CMO_MktVal_M decimal(18, 2) NULL,
	Baa_CMO_ParVal_M decimal(18, 2) NULL,
	Ba_CMO_MktVal_M decimal(18, 2) NULL,
	Ba_CMO_ParVal_M decimal(18, 2) NULL,
	B_CMO_MktVal_M decimal(18, 2) NULL,
	B_CMO_ParVal_M decimal(18, 2) NULL,
	CaaAndBelow_CMO_MktVal_M decimal(18, 2) NULL,
	CaaAndBelow_CMO_ParVal_M decimal(18, 2) NULL,
	Unrated_CMO_MktVal_M decimal(18, 2) NULL,
	Unrated_CMO_ParVal_M decimal(18, 2) NULL,
	Aaa_CorpCMO_MktVal_M decimal(18, 2) NULL,
	Aaa_CorpCMO_ParVal_M decimal(18, 2) NULL,
	Aa_CorpCMO_MktVal_M decimal(18, 2) NULL,
	Aa_CorpCMO_ParVal_M decimal(18, 2) NULL,
	A_CorpCMO_MktVal_M decimal(18, 2) NULL,
	A_CorpCMO_ParVal_M decimal(18, 2) NULL,
	Baa_CorpCMO_MktVal_M decimal(18, 2) NULL,
	Baa_CorpCMO_ParVal_M decimal(18, 2) NULL,
	Ba_CorpCMO_MktVal_M decimal(18, 2) NULL,
	Ba_CorpCMO_ParVal_M decimal(18, 2) NULL,
	B_CorpCMO_MktVal_M decimal(18, 2) NULL,
	B_CorpCMO_ParVal_M decimal(18, 2) NULL,
	CandBelow_CorpCMO_MktVal_M decimal(18, 2) NULL,
	CandBelow_CorpCMO_ParVal_M decimal(18, 2) NULL,
	Unrated_CorpCMO_MktVal_M decimal(18, 2) NULL,
	Unrated_CorpCMO_ParVal_M decimal(18, 2) NULL,
	Aaa_ConvtBond_MktVal_M decimal(18, 2) NULL,
	Aaa_ConvtBond_ParVal_M decimal(18, 2) NULL,
	Aa_ConvtBond_MktVal_M decimal(18, 2) NULL,
	Aa_ConvtBond_ParVal_M decimal(18, 2) NULL,
	A_ConvtBond_MktVal_M decimal(18, 2) NULL,
	A_ConvtBond_ParVal_M decimal(18, 2) NULL,
	Baa_ConvtBond_MktVal_M decimal(18, 2) NULL,
	Baa_ConvtBond_ParVal_M decimal(18, 2) NULL,
	Ba_ConvtBond_MktVal_M decimal(18, 2) NULL,
	Ba_ConvtBond_ParVal_M decimal(18, 2) NULL,
	B_ConvtBond_MktVal_M decimal(18, 2) NULL,
	B_ConvtBond_ParVal_M decimal(18, 2) NULL,
	CaaBelow_ConvtBond_MktVal_M decimal(18, 2) NULL,
	CaaBelow_ConvtBond_ParVal_M decimal(18, 2) NULL,
	Unrated_ConvtBond_MktVal_M decimal(18, 2) NULL,
	Unrated_ConvtBond_ParVal_M decimal(18, 2) NULL,
	Aaa_CorpBond_MktVal_M decimal(18, 2) NULL,
	Aaa_CorpBond_ParVal_M decimal(18, 2) NULL,
	Aa_CorpBond_MktVal_M decimal(18, 2) NULL,
	Aa_CorpBond_ParVal_M decimal(18, 2) NULL,
	A_CorpBond_MktVal_M decimal(18, 2) NULL,
	A_CorpBond_ParVal_M decimal(18, 2) NULL,
	Baa_CorpBond_MktVal_M decimal(18, 2) NULL,
	Baa_CorpBond_ParVal_M decimal(18, 2) NULL,
	Ba_CorpBond_MktVal_M decimal(18, 2) NULL,
	Ba_CorpBond_ParVal_M decimal(18, 2) NULL,
	B_CorpBond_MktVal_M decimal(18, 2) NULL,
	B_CorpBond_ParVal_M decimal(18, 2) NULL,
	CaaBelow_CorpBond_MktVal_M decimal(18, 2) NULL,
	CaaBelow_CorpBond_ParVal_M decimal(18, 2) NULL,
	Unrated_CorpBond_MktVal_M decimal(18, 2) NULL,
	Unrated_CorpBond_ParVal_M decimal(18, 2) NULL,
	Aaa_HighYield_MktVal_M decimal(18, 2) NULL,
	Aaa_HighYield_ParVal_M decimal(18, 2) NULL,
	Aa_HighYield_MktVal_M decimal(18, 2) NULL,
	Aa_HighYield_ParVal_M decimal(18, 2) NULL,
	A_HighYield_MktVal_M decimal(18, 2) NULL,
	A_HighYield_ParVal_M decimal(18, 2) NULL,
	Baa_HighYield_MktVal_M decimal(18, 2) NULL,
	Baa_HighYield_ParVal_M decimal(18, 2) NULL,
	Ba_HighYield_MktVal_M decimal(18, 2) NULL,
	Ba_HighYield_ParVal_M decimal(18, 2) NULL,
	B_HighYield_MktVal_M decimal(18, 2) NULL,
	B_HighYield_ParVal_M decimal(18, 2) NULL,
	CaaAndBelow_HighYield_MktVal_M decimal(18, 2) NULL,
	CaaAndBelow_HighYield_ParVal_M decimal(18, 2) NULL,
	Unrated_HighYield_MktVal_M decimal(18, 2) NULL,
	Unrated_HighYield_ParVal_M decimal(18, 2) NULL,
	Aaa_EmgMktDebt_MktVal_M decimal(18, 2) NULL,
	Aaa_EmgMktDebt_ParVal_M decimal(18, 2) NULL,
	Aa_EmgMktDebt_MktVal_M decimal(18, 2) NULL,
	Aa_EmgMktDebt_ParVal_M decimal(18, 2) NULL,
	A_EmgMktDebt_MktVal_M decimal(18, 2) NULL,
	A_EmgMktDebt_ParVal_M decimal(18, 2) NULL,
	Baa_EmgMktDebt_MktVal_M decimal(18, 2) NULL,
	Baa_EmgMktDebt_ParVal_M decimal(18, 2) NULL,
	Ba_EmgMktDebt_MktVal_M decimal(18, 2) NULL,
	Ba_EmgMktDebt_ParVal_M decimal(18, 2) NULL,
	B_EmgMktDebt_MktVal_M decimal(18, 2) NULL,
	B_EmgMktDebt_ParVal_M decimal(18, 2) NULL,
	CaaAndBelow_EmgMktDebt_MktVal_M decimal(18, 2) NULL,
	CaaAndBelow_EmgMktDebt_ParVal_M decimal(18, 2) NULL,
	Unrated_EmgMktDebt_MktVal_M decimal(18, 2) NULL,
	Unrated_EmgMktDebt_ParVal_M decimal(18, 2) NULL,
	Aaa_NonUSGov_MktVal_M decimal(18, 2) NULL,
	Aaa_NonUSGov_ParVal_M decimal(18, 2) NULL,
	Aa_NonUSGov_MktVal_M decimal(18, 2) NULL,
	Aa_NonUSGov_ParVal_M decimal(18, 2) NULL,
	A_NonUSGov_MktVal_M decimal(18, 2) NULL,
	A_NonUSGov_ParVal_M decimal(18, 2) NULL,
	Baa_NonUSGov_MktVal_M decimal(18, 2) NULL,
	Baa_NonUSGov_ParVal_M decimal(18, 2) NULL,
	Ba_NonUSGov_MktVal_M decimal(18, 2) NULL,
	Ba_NonUSGov_ParVal_M decimal(18, 2) NULL,
	B_NonUSGov_MktVal_M decimal(18, 2) NULL,
	B_NonUSGov_ParVal_M decimal(18, 2) NULL,
	CaaAndBelow_NonUSGov_MktVal_M decimal(18, 2) NULL,
	CaaAndBelow_NonUSGov_ParVal_M decimal(18, 2) NULL,
	Unrated_NonUSGov_MktVal_M decimal(18, 2) NULL,
	Unrated_NonUSGov_ParVal_M decimal(18, 2) NULL,
	Aaa_GlblCorpFix_MktVal_M decimal(18, 2) NULL,
	Aaa_GlblCorpFix_ParVal_M decimal(18, 2) NULL,
	Aa_GlblCorpFix_MktVal_M decimal(18, 2) NULL,
	Aa_GlblCorpFix_ParVal_M decimal(18, 2) NULL,
	A_GlblCorpFix_MktVal_M decimal(18, 2) NULL,
	A_GlblCorpFix_ParVal_M decimal(18, 2) NULL,
	Baa_GlblCorpFix_MktVal_M decimal(18, 2) NULL,
	Baa_GlblCorpFix_ParVal_M decimal(18, 2) NULL,
	Ba_GlblCorpFix_MktVal_M decimal(18, 2) NULL,
	Ba_GlblCorpFix_ParVal_M decimal(18, 2) NULL,
	B_GlblCorpFix_MktVal_M decimal(18, 2) NULL,
	B_GlblCorpFix_ParVal_M decimal(18, 2) NULL,
	CaaBelow_GlblCorpFix_MktVal_M decimal(18, 2) NULL,
	CaaBelow_GlblCorpFix_ParVal_M decimal(18, 2) NULL,
	Unrated_GlblCorpFix_MktVal_M decimal(18, 2) NULL,
	Unrated_GlblCorpFix_ParVal_M decimal(18, 2) NULL,
	A_CorePlus_MktVal_M decimal(18, 2) NULL,
	A_CorePlus_ParVal_M decimal(18, 2) NULL,
	Baa_CommLoan_MktVal_M decimal(18, 2) NULL,
	Baa_CommLoan_ParVal_M decimal(18, 2) NULL,
	Ba_CommLoan_MktVal_M decimal(18, 2) NULL,
	Ba_CommLoan_ParVal_M decimal(18, 2) NULL,
	B_CommLoan_MktVal_M decimal(18, 2) NULL,
	B_CommLoan_ParVal_M decimal(18, 2) NULL,
	CaaBelow_CommLoan_MktVal_M decimal(18, 2) NULL,
	CaaBelow_CommLoan_ParVal_M decimal(18, 2) NULL,
	Unrated_CommLoan_MktVal_M decimal(18, 2) NULL,
	Unrated_CommLoan_ParVal_M decimal(18, 2) NULL,
	Aaa_SecLendCol_MktVal_M decimal(18, 2) NULL,
	Aaa_SecLendCol_ParVal_M decimal(18, 2) NULL,
	Aa_SecLendCol_MktVal_M decimal(18, 2) NULL,
	Aa_SecLendCol_ParVal_M decimal(18, 2) NULL,
	A_SecLendCol_MktVal_M decimal(18, 2) NULL,
	A_SecLendCol_ParVal_M decimal(18, 2) NULL,
	Baa_SecLendCol_MktVal_M decimal(18, 2) NULL,
	Baa_SecLendCol_ParVal_M decimal(18, 2) NULL,
	Ba_SecLendCol_MktVal_M decimal(18, 2) NULL,
	Ba_SecLendCol_ParVal_M decimal(18, 2) NULL,
	B_SecLendCol_MktVal_M decimal(18, 2) NULL,
	B_SecLendCol_ParVal_M decimal(18, 2) NULL,
	CaaBelow_SecLendCol_MktVal_M decimal(18, 2) NULL,
	CaaBelow_SecLendCol_ParVal_M decimal(18, 2) NULL,
	P1_SecLend_MktVal_M decimal(18, 2) NULL,
	P1_SecLend_ParVal_M decimal(18, 2) NULL,
	P2_SecLend_MktVal_M decimal(18, 2) NULL,
	P2_SecLend_ParVal_M decimal(18, 2) NULL,
	Unrated_SecLendCol_MktVal_M decimal(18, 2) NULL,
	Unrated_SecLendCol_ParVal_M decimal(18, 2) NULL,
	Aaa_Cash_MktVal_M decimal(18, 2) NULL,
	Aaa_Cash_ParVal_M decimal(18, 2) NULL,
	Aa_Cash_MktVal_M decimal(18, 2) NULL,
	Aa_Cash_ParVal_M decimal(18, 2) NULL,
	A_Cash_MktVal_M decimal(18, 2) NULL,
	A_Cash_ParVal_M decimal(18, 2) NULL,
	Baa_Cash_MktVal_M decimal(18, 2) NULL,
	Baa_Cash_ParVal_M decimal(18, 2) NULL,
	GovGuaranteed_Cash_MktVal_M decimal(18, 2) NULL,
	GovGuaranteed_Cash_ParVal_M decimal(18, 2) NULL,
	P1_Cash_MktVal_M decimal(18, 2) NULL,
	P1_Cash_ParVal_M decimal(18, 2) NULL,
	Unrated_Cash_MktVal_M decimal(18, 2) NULL,
	Unrated_Cash_ParVal_M decimal(18, 2) NULL,
	Aaa_ABS_MktVal_M decimal(18, 2) NULL,
	Aaa_ABS_ParVal_M decimal(18, 2) NULL,
	Aa_ABS_MktVal_M decimal(18, 2) NULL,
	Aa_ABS_ParVal_M decimal(18, 2) NULL,
	A_ABS_MktVal_M decimal(18, 2) NULL,
	A_ABS_ParVal_M decimal(18, 2) NULL,
	Baa_ABS_MktVal_M decimal(18, 2) NULL,
	Baa_ABS_ParVal_M decimal(18, 2) NULL,
	Ba_ABS_MktVal_M decimal(18, 2) NULL,
	Ba_ABS_ParVal_M decimal(18, 2) NULL,
	B_ABS_MktVal_M decimal(18, 2) NULL,
	B_ABS_ParVal_M decimal(18, 2) NULL,
	CaaAndBelow_ABS_MktVal_M decimal(18, 2) NULL,
	CaaAndBelow_ABS_ParVal_M decimal(18, 2) NULL,
	Unrated_ABS_MktVal_M decimal(18, 2) NULL,
	Unrated_ABS_ParVal_M decimal(18, 2) NULL,
	Aaa_GovAg_MktVal_M decimal(18, 2) NULL,
	Aaa_GovAg_ParVal_M decimal(18, 2) NULL,
	Aa_GovAg_MktVal_M decimal(18, 2) NULL,
	Aa_GovAg_ParVal_M decimal(18, 2) NULL,
	A_GovAg_MktVal_M decimal(18, 2) NULL,
	A_GovAg_ParVal_M decimal(18, 2) NULL,
	Baa_GovAg_MktVal_M decimal(18, 2) NULL
    )"""

PensionInvestmentFees_table = """CREATE TABLE PensionInvestmentFees(
	ppd_id float NULL,
	PlanName varchar(255) NULL,
	fy float NULL,
	Notes_Fees varchar(255) NULL,
	NoFeeData float NULL,
	group_fees varchar(255) NULL,
	group_id varchar(255) NULL,
	est_proportion decimal(7, 5) NULL,
	EQTotal_Fee decimal(18, 2) NULL,
	FITotal_Fee decimal(18, 2) NULL,
	RETotal_Fee decimal(18, 2) NULL,
	AltMiscTotal_Fee decimal(18, 2) NULL,
	PETotal_Fee decimal(18, 2) NULL,
	HFTotal_Fee decimal(18, 2) NULL,
	COMDTotal_Fee decimal(18, 2) NULL,
	CashTotal_Fee decimal(18, 2) NULL,
	OtherTotal_Fee decimal(18, 2) NULL
)"""

PensionInvestmentPerformanceDetailed_table = """CREATE TABLE PensionInvestmentPerformanceDetailed(
	ppd_id float NULL,
	PlanName varchar(255) NULL,
	EEGroupID float NULL,
	TierID float NULL,
	fy float NULL,
	EQDomesticMisc_Rtrn varchar(255) NULL,
	EQDomesticMisc_BnchmrkRtrn varchar(255) NULL,
	EQDomesticMisc_Bnchmrk varchar(255) NULL,
	EQDomesticMisc_Trgt varchar(255) NULL,
	EQDomesticMisc_Actl varchar(255) NULL,
	EQDomesticLarge_Rtrn varchar(255) NULL,
	EQDomesticLarge_BnchmrkRtrn varchar(255) NULL,
	EQDomesticLarge_Bnchmrk varchar(255) NULL,
	EQDomesticLarge_Trgt varchar(255) NULL,
	EQDomesticLarge_Actl varchar(255) NULL,
	EQDomesticMid_Rtrn varchar(255) NULL,
	EQDomesticMid_BnchmrkRtrn varchar(255) NULL,
	EQDomesticMid_Bnchmrk varchar(255) NULL,
	EQDomesticMid_Trgt varchar(255) NULL,
	EQDomesticMid_Actl varchar(255) NULL,
	EQDomesticSmall_Rtrn varchar(255) NULL,
	EQDomesticSmall_BnchmrkRtrn varchar(255) NULL,
	EQDomesticSmall_Bnchmrk varchar(255) NULL,
	EQDomesticSmall_Trgt varchar(255) NULL,
	EQDomesticSmall_Actl varchar(255) NULL,
	EQIntlMisc_Rtrn varchar(255) NULL,
	EQIntlMisc_BnchmrkRtrn varchar(255) NULL,
	EQIntlMisc_Bnchmrk varchar(255) NULL,
	EQIntlMisc_Trgt varchar(255) NULL,
	EQIntlMisc_Actl varchar(255) NULL,
	EQIntlDev_Rtrn varchar(255) NULL,
	EQIntlDev_BnchmrkRtrn varchar(255) NULL,
	EQIntlDev_Bnchmrk varchar(255) NULL,
	EQIntlDev_Trgt varchar(255) NULL,
	EQIntlDev_Actl varchar(255) NULL,
	EQIntlEmerg_Rtrn varchar(255) NULL,
	EQIntlEmerg_BnchmrkRtrn varchar(255) NULL,
	EQIntlEmerg_Bnchmrk varchar(255) NULL,
	EQIntlEmerg_Trgt varchar(255) NULL,
	EQIntlEmerg_Actl varchar(255) NULL,
	EQIntlPass_Rtrn varchar(255) NULL,
	EQIntlPass_BnchmrkRtrn varchar(255) NULL,
	EQIntlPass_Bnchmrk varchar(255) NULL,
	EQIntlPass_Trgt varchar(255) NULL,
	EQIntlPass_Actl varchar(255) NULL,
	EQIntlActv_Rtrn varchar(255) NULL,
	EQIntlActv_BnchmrkRtrn varchar(255) NULL,
	EQIntlActv_Bnchmrk varchar(255) NULL,
	EQIntlActv_Trgt varchar(255) NULL,
	EQIntlActv_Actl varchar(255) NULL,
	FIDomestic_Rtrn varchar(255) NULL,
	FIDomestic_BnchmrkRtrn varchar(255) NULL,
	FIDomestic_Bnchmrk varchar(255) NULL,
	FIDomestic_Trgt varchar(255) NULL,
	FIDomestic_Actl varchar(255) NULL,
	FIIntl_Rtrn varchar(255) NULL,
	FIIntl_BnchmrkRtrn varchar(255) NULL,
	FIIntl_Bnchmrk varchar(255) NULL,
	FIIntl_Trgt varchar(255) NULL,
	FIIntl_Actl varchar(255) NULL,
	Cash_Rtrn varchar(255) NULL,
	Cash_BnchmrkRtrn varchar(255) NULL,
	Cash_Bnchmrk varchar(255) NULL,
	Cash_Trgt varchar(255) NULL,
	Cash_Actl varchar(255) NULL,
	Other_Rtrn varchar(255) NULL,
	Other_BnchmrkRtrn varchar(255) NULL,
	Other_Bnchmrk varchar(255) NULL,
	Other_Trgt varchar(255) NULL,
	Other_Actl varchar(255) NULL,
	MiscEQFI_Rtrn varchar(255) NULL,
	MiscEQFI_BnchmrkRtrn varchar(255) NULL,
	MiscEQFI_Bnchmrk varchar(255) NULL,
	MiscEQFI_Trgt varchar(255) NULL,
	MiscEQFI_Actl varchar(255) NULL,
	EQMisc_Rtrn varchar(255) NULL,
	EQMisc_BnchmrkRtrn varchar(255) NULL,
	EQMisc_Bnchmrk varchar(255) NULL,
	EQMisc_Trgt varchar(255) NULL,
	EQMisc_Actl varchar(255) NULL,
	EQCore_Rtrn varchar(255) NULL,
	EQCore_BnchmrkRtrn varchar(255) NULL,
	EQCore_Bnchmrk varchar(255) NULL,
	EQCore_Trgt varchar(255) NULL,
	EQCore_Actl varchar(255) NULL,
	EQLarge_Rtrn varchar(255) NULL,
	EQLarge_BnchmrkRtrn varchar(255) NULL,
	EQLarge_Bnchmrk varchar(255) NULL,
	EQLarge_Trgt varchar(255) NULL,
	EQLarge_Actl varchar(255) NULL,
	EQMicro_Rtrn varchar(255) NULL,
	EQMicro_BnchmrkRtrn varchar(255) NULL,
	EQMicro_Bnchmrk varchar(255) NULL,
	EQMicro_Trgt varchar(255) NULL,
	EQMicro_Actl varchar(255) NULL,
	EQOpportunistic_Rtrn varchar(255) NULL,
	EQOpportunistic_BnchmrkRtrn varchar(255) NULL,
	EQOpportunistic_Bnchmrk varchar(255) NULL,
	EQOpportunistic_Trgt varchar(255) NULL,
	EQOpportunistic_Actl varchar(255) NULL,
	EQSmall_Rtrn varchar(255) NULL,
	EQSmall_BnchmrkRtrn varchar(255) NULL,
	EQSmall_Bnchmrk varchar(255) NULL,
	EQSmall_Trgt varchar(255) NULL,
	EQSmall_Actl varchar(255) NULL,
	EQSocialResp_Rtrn varchar(255) NULL,
	EQSocialResp_BnchmrkRtrn varchar(255) NULL,
	EQSocialResp_Bnchmrk varchar(255) NULL,
	EQSocialResp_Trgt varchar(255) NULL,
	EQSocialResp_Actl varchar(255) NULL,
	EQSecLend_Rtrn varchar(255) NULL,
	EQSecLend_BnchmrkRtrn varchar(255) NULL,
	EQSecLend_Bnchmrk varchar(255) NULL,
	EQSecLend_Trgt varchar(255) NULL,
	EQSecLend_Actl varchar(255) NULL,
	EQGlobal_Rtrn varchar(255) NULL,
	EQGlobal_BnchmrkRtrn varchar(255) NULL,
	EQGlobal_Bnchmrk varchar(255) NULL,
	EQGlobal_Trgt varchar(255) NULL,
	EQGlobal_Actl varchar(255) NULL,
	EQGlobalGrowth_Rtrn varchar(255) NULL,
	EQGlobalGrowth_BnchmrkRtrn varchar(255) NULL,
	EQGlobalGrowth_Bnchmrk varchar(255) NULL,
	EQGlobalGrowth_Trgt varchar(255) NULL,
	EQGlobalGrowth_Actl varchar(255) NULL,
	FIMisc_Rtrn varchar(255) NULL,
	FIMisc_BnchmrkRtrn varchar(255) NULL,
	FIMisc_Bnchmrk varchar(255) NULL,
	FIMisc_Trgt varchar(255) NULL,
	FIMisc_Actl varchar(255) NULL,
	FIBelowInvestGrd_Rtrn varchar(255) NULL,
	FIBelowInvestGrd_BnchmrkRtrn varchar(255) NULL,
	FIBelowInvestGrd_Bnchmrk varchar(255) NULL,
	FIBelowInvestGrd_Trgt varchar(255) NULL,
	FIBelowInvestGrd_Actl varchar(255) NULL,
	FICash_Rtrn varchar(255) NULL,
	FICash_BnchmrkRtrn varchar(255) NULL,
	FICash_Bnchmrk varchar(255) NULL,
	FICash_Trgt varchar(255) NULL,
	FICash_Actl varchar(255) NULL,
	FIConv_Rtrn varchar(255) NULL,
	FIConv_BnchmrkRtrn varchar(255) NULL,
	FIConv_Bnchmrk varchar(255) NULL,
	FIConv_Trgt varchar(255) NULL,
	FIConv_Actl varchar(255) NULL,
	FICore_Rtrn varchar(255) NULL,
	FICore_BnchmrkRtrn varchar(255) NULL,
	FICore_Bnchmrk varchar(255) NULL,
	FICore_Trgt varchar(255) NULL,
	FICore_Actl varchar(255) NULL,
	FIETI_Rtrn varchar(255) NULL,
	FIETI_BnchmrkRtrn varchar(255) NULL,
	FIETI_Bnchmrk varchar(255) NULL,
	FIETI_Trgt varchar(255) NULL,
	FIETI_Actl varchar(255) NULL,
	FIInvestGrd_Rtrn varchar(255) NULL,
	FIInvestGrd_BnchmrkRtrn varchar(255) NULL,
	FIInvestGrd_Bnchmrk varchar(255) NULL,
	FIInvestGrd_Trgt varchar(255) NULL,
	FIInvestGrd_Actl varchar(255) NULL,
	FILoans_Rtrn varchar(255) NULL,
	FILoans_BnchmrkRtrn varchar(255) NULL,
	FILoans_Bnchmrk varchar(255) NULL,
	FILoans_Trgt varchar(255) NULL,
	FILoans_Actl varchar(255) NULL,
	FIFundsFunds_Rtrn varchar(255) NULL,
	FIFundsFunds_BnchmrkRtrn varchar(255) NULL,
	FIFundsFunds_Bnchmrk varchar(255) NULL,
	FIFundsFunds_Trgt varchar(255) NULL,
	FIFundsFunds_Actl varchar(255) NULL,
	FINominal_Rtrn varchar(255) NULL,
	FINominal_BnchmrkRtrn varchar(255) NULL,
	FINominal_Bnchmrk varchar(255) NULL,
	FINominal_Trgt varchar(255) NULL,
	FINominal_Actl varchar(255) NULL,
	FINonCore_Rtrn varchar(255) NULL,
	FINonCore_BnchmrkRtrn varchar(255) NULL,
	FINonCore_Bnchmrk varchar(255) NULL,
	FINonCore_Trgt varchar(255) NULL,
	FINonCore_Actl varchar(255) NULL,
	FIStructured_Rtrn varchar(255) NULL,
	FIStructured_BnchmrkRtrn varchar(255) NULL,
	FIStructured_Bnchmrk varchar(255) NULL,
	FIStructured_Trgt varchar(255) NULL,
	FIStructured_Actl varchar(255) NULL,
	FITIPS_Rtrn varchar(255) NULL,
	FITIPS_BnchmrkRtrn varchar(255) NULL,
	FITIPS_Bnchmrk varchar(255) NULL,
	FITIPS_Trgt varchar(255) NULL,
	FITIPS_Actl varchar(255) NULL,
	FITreasury_Rtrn varchar(255) NULL,
	FITreasury_BnchmrkRtrn varchar(255) NULL,
	FITreasury_Bnchmrk varchar(255) NULL,
	FITreasury_Trgt varchar(255) NULL,
	FITreasury_Actl varchar(255) NULL,
	FICorpBonds_Rtrn varchar(255) NULL,
	FICorpBonds_BnchmrkRtrn varchar(255) NULL,
	FICorpBonds_Bnchmrk varchar(255) NULL,
	FICorpBonds_Trgt varchar(255) NULL,
	FICorpBonds_Actl varchar(255) NULL,
	FIValue_Rtrn varchar(255) NULL,
	FIValue_BnchmrkRtrn varchar(255) NULL,
	FIValue_Bnchmrk varchar(255) NULL,
	FIValue_Trgt varchar(255) NULL,
	FIValue_Actl varchar(255) NULL,
	FIGlobal_Rtrn varchar(255) NULL,
	FIGlobal_BnchmrkRtrn varchar(255) NULL,
	FIGlobal_Bnchmrk varchar(255) NULL,
	FIGlobal_Trgt varchar(255) NULL,
	FIGlobal_Actl varchar(255) NULL,
	FIEmerg_Rtrn varchar(255) NULL,
	FIEmerg_BnchmrkRtrn varchar(255) NULL,
	FIEmerg_Bnchmrk varchar(255) NULL,
	FIEmerg_Trgt varchar(255) NULL,
	FIEmerg_Actl varchar(255) NULL,
	FIHighYield_Rtrn varchar(255) NULL,
	FIHighYield_BnchmrkRtrn varchar(255) NULL,
	FIHighYield_Bnchmrk varchar(255) NULL,
	FIHighYield_Trgt varchar(255) NULL,
	FIHighYield_Actl varchar(255) NULL,
	FIMortgage_Rtrn varchar(255) NULL,
	FIMortgage_BnchmrkRtrn varchar(255) NULL,
	FIMortgage_Bnchmrk varchar(255) NULL,
	FIMortgage_Trgt varchar(255) NULL,
	FIMortgage_Actl varchar(255) NULL,
	FIAlt_Rtrn varchar(255) NULL,
	FIAlt_BnchmrkRtrn varchar(255) NULL,
	FIAlt_Bnchmrk varchar(255) NULL,
	FIAlt_Trgt varchar(255) NULL,
	FIAlt_Actl varchar(255) NULL,
	FIOpp_Rtrn varchar(255) NULL,
	FIOpp_BnchmrkRtrn varchar(255) NULL,
	FIOpp_Bnchmrk varchar(255) NULL,
	FIOpp_Trgt varchar(255) NULL,
	FIOpp_Actl varchar(255) NULL,
	FIGIPS_Rtrn varchar(255) NULL,
	FIGIPS_BnchmrkRtrn varchar(255) NULL,
	FIGIPS_Bnchmrk varchar(255) NULL,
	FIGIPS_Trgt varchar(255) NULL,
	FIGIPS_Actl varchar(255) NULL,
	AltMisc_Rtrn varchar(255) NULL,
	AltMisc_BnchmrkRtrn varchar(255) NULL,
	AltMisc_Bnchmrk varchar(255) NULL,
	AltMisc_Trgt varchar(255) NULL,
	AltMisc_Actl varchar(255) NULL,
	MultiClass_Rtrn varchar(255) NULL,
	MultiClass_BnchmrkRtrn varchar(255) NULL,
	MultiClass_Bnchmrk varchar(255) NULL,
	MultiClass_Trgt varchar(255) NULL,
	MultiClass_Actl varchar(255) NULL,
	EQPrivate_Rtrn varchar(255) NULL,
	EQPrivate_BnchmrkRtrn varchar(255) NULL,
	EQPrivate_Bnchmrk varchar(255) NULL,
	EQPrivate_Trgt varchar(255) NULL,
	EQPrivate_Actl varchar(255) NULL
)"""

PensionTopStocksTopBonds_table = """CREATE TABLE PensionTopStocksTopBonds(
	ppd_id float NULL,
	PlanName varchar(255) NULL,
	fy float NULL,
	est_proportion float NULL,
	StockLargest_share float NULL,
	StockLargestFive_share float NULL,
	StockLargestTen_share float NULL,
	BondLargest_share float NULL,
	BondLargestFive_share float NULL,
	BondLargestTen_share float NULL,
	Stock1_name varchar(255) NULL,
	Stock1_ticker varchar(255) NULL,
	Stock1_dollars float NULL,
	Stock2_name varchar(255) NULL,
	Stock2_ticker varchar(255) NULL,
	Stock2_dollars float NULL,
	Stock3_name varchar(255) NULL,
	Stock3_ticker varchar(255) NULL,
	Stock3_dollars float NULL,
	Stock4_name varchar(255) NULL,
	Stock4_ticker varchar(255) NULL,
	Stock4_dollars float NULL,
	Stock5_name varchar(255) NULL,
	Stock5_ticker varchar(255) NULL,
	Stock5_dollars float NULL,
	Stock6_name varchar(255) NULL,
	Stock6_ticker varchar(255) NULL,
	Stock6_dollars float NULL,
	Stock7_name varchar(255) NULL,
	Stock7_ticker varchar(255) NULL,
	Stock7_dollars float NULL,
	Stock8_name varchar(255) NULL,
	Stock8_ticker varchar(255) NULL,
	Stock8_dollars float NULL,
	Stock9_name varchar(255) NULL,
	Stock9_ticker varchar(255) NULL,
	Stock9_dollars float NULL,
	Stock10_name varchar(255) NULL,
	Stock10_ticker varchar(255) NULL,
	Stock10_dollars float NULL,
	Bond1_name varchar(255) NULL,
	Bond1_dollars float NULL,
	Bond1_couponrate varchar(255) NULL,
	Bond1_maturityyr float NULL,
	Bond2_name varchar(255) NULL,
	Bond2_dollars float NULL,
	Bond2_couponrate varchar(255) NULL,
	Bond2_maturityyr varchar(255) NULL,
	Bond3_name varchar(255) NULL,
	Bond3_dollars float NULL,
	Bond3_couponrate varchar(255) NULL,
	Bond3_maturityyr float NULL,
	Bond4_name varchar(255) NULL,
	Bond4_dollars float NULL,
	Bond4_couponrate varchar(255) NULL,
	Bond4_maturityyr float NULL,
	Bond5_name varchar(255) NULL,
	Bond5_dollars float NULL,
	Bond5_couponrate varchar(255) NULL,
	Bond5_maturityyr float NULL,
	Bond6_name varchar(255) NULL,
	Bond6_dollars float NULL,
	Bond6_couponrate varchar(255) NULL,
	Bond6_maturityyr float NULL,
	Bond7_name varchar(255) NULL,
	Bond7_dollars float NULL,
	Bond7_couponrate varchar(255) NULL,
	Bond7_maturityyr float NULL,
	Bond8_name varchar(255) NULL,
	Bond8_dollars float NULL,
	Bond8_couponrate varchar(255) NULL,
	Bond8_maturityyr float NULL,
	Bond9_name varchar(255) NULL,
	Bond9_dollars float NULL,
	Bond9_couponrate varchar(255) NULL,
	Bond9_maturityyr float NULL,
	Bond10_name varchar(255) NULL,
	Bond10_dollars float NULL,
	Bond10_couponrate varchar(255) NULL,
	Bond10_maturityyr float NULL,
	Bond_name varchar(255) NULL
)"""

PFPlan_PPDSupplement_table = """CREATE TABLE PFPlan_PPDSupplement(
	pf_id float NULL,
	StateAbbrev varchar(255) NULL,
	PlanName varchar(255) NULL,
	fy int NULL,
	ActAssets_GASB float NULL,
	ActLiabilities_GASB float NULL,
	ActFundedRatio_GASB float NULL,
	UAAL_GASB float NULL,
	ActLiabilities_other decimal(18, 2) NULL,
	payroll float NULL,
	RequiredContribution float NULL,
	PercentReqContPaid float NULL,
	ARC float NULL,
	PercentARCPaid float NULL,
	TotalPensionLiability decimal(18, 2) NULL,
	NetPosition decimal(18, 2) NULL,
	NetPensionLiability decimal(18, 2) NULL,
	ADEC float NULL,
	AEC float NULL,
	CoveredPayroll_GASB67 float NULL,
	PercentADEC float NULL,
	ActAssets_est float NULL,
	ActLiabilities_est float NULL,
	ActFundedRatio_est float NULL,
	InflationAssumption_GASB float NULL,
	InvestmentReturnAssumption_GASB float NULL,
	ActCostMeth_GASB varchar(255) NULL,
	ActCostMethCode_GASB float NULL,
	AssetValMeth_GASB varchar(255) NULL,
	AssetValMethCode_GASB float NULL,
	AssetSmoothingPeriod_GASB float NULL,
	FundingMeth_GASB varchar(255) NULL,
	FundingMethCode1_GASB float NULL,
	FundingMethCode2_GASB float NULL,
	UAALAmortPeriod_GASB float NULL,
	BlendedDiscountRate float NULL,
	actives_tot int NULL,
	InactiveVestedMembers int NULL,
	beneficiaries_tot int NULL,
	OtherMembers int NULL,
	TotMembership int NULL,
	BeneficiaryAge_avg float NULL,
	ServiceRetireeAge_avg float NULL,
	ActiveAge_avg float NULL,
	ActiveTenure_avg float NULL,
	ActiveSalaries float NULL,
	ActiveSalary_avg float NULL,
	benefits_tot float NULL,
	BeneficiaryBenefit_avg float NULL,
	benefits_ServiceRetirees float NULL,
	ServiceRetTenure_avg float NULL,
	ServiceRetBenefit_avg float NULL,
	benefits_DisabilityRetirees float NULL,
	beneficiaries_survivors float NULL,
	contrib_EE_regular float NULL,
	contrib_ER_regular float NULL,
	contrib_ER_state float NULL,
	contrib_EE_PurchaseService float NULL,
	contrib_EE_other float NULL,
	contrib_ER_other float NULL,
	contrib_other float NULL,
	contrib_tot float NULL,
	FairValueChange_investments float NULL,
	FairValueChange_RealEstate float NULL,
	income_interest float NULL,
	income_dividends float NULL,
	income_InterestAndDividends float NULL,
	income_RealEstate float NULL,
	income_PrivateEquity float NULL,
	income_alternatives float NULL,
	income_international float NULL,
	income_OtherInvestments float NULL,
	expense_RealEstate float NULL,
	expense_PrivateEquity float NULL,
	expense_alternatives float NULL,
	expense_OtherInvestments float NULL,
	expense_investments float NULL,
	income_SecuritiesLending float NULL,
	expense_SecuritiesLending float NULL,
	income_SecuritiesLendingRebate float NULL,
	income_OtherAdditions float NULL,
	income_net float NULL,
	expense_TotBenefits float NULL,
	expense_RetBenefits float NULL,
	expense_DisabilityBenefits float NULL,
	expense_DeathBenefits float NULL,
	expense_DROPBenefits float NULL,
	expense_SurvivorBenefits float NULL,
	expense_COLABenefits float NULL,
	expense_LumpSumBenefits float NULL,
	expense_OtherBenefits float NULL,
	expense_refunds float NULL,
	expense_AdminExpenses float NULL,
	expense_Depreciation float NULL,
	expense_OtherDeductions float NULL,
	expense_net float NULL,
	adjustment_MktAssets float NULL,
	MktAssets_net float NULL,
	InvestmentReturn_1yr float NULL,
	InvestmentReturn_2yr float NULL,
	InvestmentReturn_3yr float NULL,
	InvestmentReturn_4yr float NULL,
	InvestmentReturn_5yr float NULL,
	InvestmentReturn_7yr float NULL,
	InvestmentReturn_8yr float NULL,
	InvestmentReturn_10yr float NULL,
	InvestmentReturn_12yr float NULL,
	InvestmentReturn_15yr float NULL,
	InvestmentReturn_20yr float NULL,
	InvestmentReturn_25yr float NULL,
	InvestmentReturn_30yr float NULL,
	InvestmentReturn_LongTerm float NULL,
	InvestmentReturn_LTStartYear float NULL,
	GrossReturns float NULL,
	InvestmentReturn_1yr_est float NULL,
	InvestmentReturn_5yr_est float NULL,
	InvestmentReturn_10yr_est float NULL,
	ContributionFY int NULL,
	NormCostRate_tot float NULL,
	NormCostRate_EE float NULL,
	NormCostRate_ER float NULL,
	ReqContRate_ER float NULL,
	ReqContRate_tot float NULL,
	NormCostAmount_tot float NULL,
	NormCostAmount_EE float NULL,
	NormCostAmount_ER float NULL,
	ReqContAmount_ER float NULL,
	ReqContAmount_tot float NULL,
	NormCostRate_tot_est float NULL,
	NormCostRate_EE_est float NULL,
	NormCostRate_ER_est float NULL,
	ReqContRate_ER_est float NULL,
	ProjectedPayroll float NULL
)"""

PPDDataLatest_table = """CREATE TABLE PPDDataLatest(
	ppd_id float NULL,
	PlanName varchar(255) NULL,
	fy float NULL,
	system_id float NULL,
	PlanFullName varchar(255) NULL,
	source_PlanBasics varchar(255) NULL,
	FiscalYearType float NULL,
	PlanInceptionYear float NULL,
	PlanClosed float NULL,
	PlanYearClosed varchar(255) NULL,
	AdministeringGovt float NULL,
	StateAbbrev varchar(255) NULL,
	StateName varchar(255) NULL,
	GovtName varchar(255) NULL,
	PlanType float NULL,
	EmployeeTypeCovered varchar(255) NULL,
	SocSecCovered float NULL,
	SocSecCovered_verbatim varchar(255) NULL,
	CostStructure varchar(255) NULL,
	EmployerType float NULL,
	CostSharing float NULL,
	BenefitsWebsite varchar(255) NULL,
	EEGroupID float NULL,
	TierID float NULL,
	ActRptDate timestamp NULL,
	fye timestamp NULL,
	ActCostMeth_GASB varchar(255) NULL,
	AssetValMeth_GASB varchar(255) NULL,
	FundingMeth_GASB varchar(255) NULL,
	InflationAssumption_GASB float NULL,
	InvestmentReturnAssumption_GASB float NULL,
	ActCostMethCode_GASB float NULL,
	AssetValMethCode_GASB float NULL,
	AssetSmoothingPeriod_GASB float NULL,
	FundingMethCode1_GASB float NULL,
	FundingMethCode2_GASB float NULL,
	UAALAmortPeriod_GASB float NULL,
	BlendedDiscountRate decimal(7, 5) NULL,
	AssetValMeth varchar(255) NULL,
	PhaseIn varchar(255) NULL,
	AssetValMeth_note varchar(255) NULL,
	ActCostMeth varchar(255) NULL,
	ActCostMeth_note varchar(255) NULL,
	FundingMeth varchar(255) NULL,
	FundingMeth_note varchar(255) NULL,
	MktAssets_Smooth varchar(255) NULL,
	ActAssets_Smooth varchar(255) NULL,
	NetFlows_smooth varchar(255) NULL,
	AssetValMethCode varchar(255) NULL,
	SmoothingReset varchar(255) NULL,
	GainlossConcept varchar(255) NULL,
	GainLossBase_1 varchar(255) NULL,
	GainLossBase_2 varchar(255) NULL,
	GainLoss decimal(18, 2) NULL,
	GainLossPeriod varchar(255) NULL,
	PhaseInPercent varchar(255) NULL,
	PhaseInPeriods varchar(255) NULL,
	PhaseInType varchar(255) NULL,
	GainLossRecognition varchar(255) NULL,
	AssetSmoothingBaseline varchar(255) NULL,
	ExpectedReturnMethod varchar(255) NULL,
	AddSubtractGainLoss varchar(255) NULL,
	UpperCorridor varchar(255) NULL,
	LowerCorridor varchar(255) NULL,
	ActCostMethCode varchar(255) NULL,
	FundMethCode_1 varchar(255) NULL,
	FundMethCode_2 varchar(255) NULL,
	PayrollGrowthAssumption float NULL,
	TotAmortPeriod varchar(255) NULL,
	RemainingAmortPeriod varchar(255) NULL,
	UAALYearEstablished varchar(255) NULL,
	WageInflation decimal(7, 5) NULL,
	ActAssets_GASB float NULL,
	ActLiabilities_GASB float NULL,
	ActFundedRatio_GASB float NULL,
	UAAL_GASB float NULL,
	ActLiabilities_other float NULL,
	payroll float NULL,
	RequiredContribution float NULL,
	PercentReqContPaid float NULL,
	TotalPensionLiability decimal(18, 2) NULL,
	NetPosition decimal(18, 2) NULL,
	NetPensionLiability decimal(18, 2) NULL,
	ActAssets_est float NULL,
	ActLiabilities_est float NULL,
	ActFundedRatio_est float NULL,
	RequiredContribution_est varchar(255) NULL,
	ActFundedRatio_GASB67 varchar(255) NULL,
	InvestmentConsultantName varchar(255) NULL,
	InvestmentConsultantCode float NULL,
	InvestmentReturn_1yr float NULL,
	InvestmentReturn_2yr varchar(255) NULL,
	InvestmentReturn_3yr float NULL,
	InvestmentReturn_4yr varchar(255) NULL,
	InvestmentReturn_5yr float NULL,
	InvestmentReturn_7yr varchar(255) NULL,
	InvestmentReturn_8yr varchar(255) NULL,
	InvestmentReturn_10yr float NULL,
	InvestmentReturn_12yr varchar(255) NULL,
	InvestmentReturn_15yr varchar(255) NULL,
	InvestmentReturn_20yr varchar(255) NULL,
	InvestmentReturn_25yr varchar(255) NULL,
	InvestmentReturn_30yr varchar(255) NULL,
	InvestmentReturn_LongTerm varchar(255) NULL,
	InvestmentReturn_LTStartYear varchar(255) NULL,
	GrossReturns varchar(255) NULL,
	GeoReturn_est float NULL,
	GeoGrowth_est float NULL,
	InvestmentReturn_1yr_est float NULL,
	InvestmentReturn_5yr_est float NULL,
	InvestmentReturn_10yr_est float NULL,
	AvgReturn_3yr float NULL,
	AvgReturn_5yr float NULL,
	AvgReturn_10yr decimal(18, 2) NULL,
	expense_SecLendMgmtFees float NULL,
	contrib_EE_regular float NULL,
	contrib_ER_regular float NULL,
	contrib_ER_state decimal(18, 2) NULL,
	contrib_EE_PurchaseService decimal(18, 2) NULL,
	contrib_EE_other decimal(18, 2) NULL,
	contrib_ER_other decimal(18, 2) NULL,
	contrib_other float NULL,
	contrib_tot float NULL,
	FairValueChange_investments float NULL,
	FairValueChange_RealEstate decimal(18, 2) NULL,
	income_interest decimal(18, 2) NULL,
	income_dividends decimal(18, 2) NULL,
	income_InterestAndDividends float NULL,
	income_RealEstate decimal(18, 2) NULL,
	income_PrivateEquity decimal(18, 2) NULL,
	income_alternatives decimal(18, 2) NULL,
	income_international decimal(18, 2) NULL,
	income_OtherInvestments decimal(18, 2) NULL,
	expense_RealEstate decimal(18, 2) NULL,
	expense_PrivateEquity decimal(18, 2) NULL,
	expense_alternatives decimal(18, 2) NULL,
	expense_OtherInvestments decimal(18, 2) NULL,
	expense_investments float NULL,
	FVChange_SecLend decimal(18, 2) NULL,
	income_SecuritiesLending float NULL,
	expense_SecuritiesLending float NULL,
	income_SecuritiesLendingRebate float NULL,
	FVChange_SecLend_UG decimal(18, 2) NULL,
	income_OtherAdditions decimal(18, 2) NULL,
	income_net float NULL,
	expense_TotBenefits float NULL,
	expense_RetBenefits float NULL,
	expense_DisabilityBenefits decimal(18, 2) NULL,
	expense_DeathBenefits decimal(18, 2) NULL,
	expense_DROPBenefits decimal(18, 2) NULL,
	expense_SurvivorBenefits decimal(18, 2) NULL,
	expense_COLABenefits decimal(18, 2) NULL,
	expense_LumpSumBenefits decimal(18, 2) NULL,
	expense_OtherBenefits float NULL,
	expense_refunds float NULL,
	expense_AdminExpenses float NULL,
	expense_Depreciation float NULL,
	expense_OtherDeductions float NULL,
	expense_net float NULL,
	adjustment_MktAssets decimal(18, 2) NULL,
	MktAssets_net float NULL,
	BegMktAssets_net float NULL,
	contrib_ER_tot float NULL,
	contrib_other_tot float NULL,
	FairValueChange_tot float NULL,
	income_interest_dividends_tot float NULL,
	expense_investments_tot float NULL,
	SecLend_tot float NULL,
	investments_net float NULL,
	expense_other_tot float NULL,
	ContributionFY float NULL,
	ActuarialFirm varchar(255) NULL,
	ActuarialFirmCode float NULL,
	NormCostRate_tot float NULL,
	NormCostRate_EE float NULL,
	NormCostRate_ER float NULL,
	ReqContRate_ER float NULL,
	ReqContRate_tot float NULL,
	NormCostAmount_tot decimal(18, 2) NULL,
	NormCostAmount_EE decimal(18, 2) NULL,
	NormCostAmount_ER decimal(18, 2) NULL,
	ReqContAmount_ER decimal(18, 2) NULL,
	ReqContAmount_tot decimal(18, 2) NULL,
	NormCostRate_tot_est float NULL,
	NormCostRate_EE_est float NULL,
	NormCostRate_ER_est float NULL,
	ReqContRate_ER_est float NULL,
	ProjectedPayroll decimal(18, 2) NULL,
	UAALRate float NULL,
	beneficiaries_DisabilityRetirees float NULL,
	beneficiaries_DependentSurvivors varchar(255) NULL,
	actives_tot float NULL,
	ActiveSalaries float NULL,
	ActiveAge_avg varchar(255) NULL,
	ActiveTenure_avg varchar(255) NULL,
	ActiveSalary_avg float NULL,
	InactiveVestedMembers float NULL,
	InactiveNonVested varchar(255) NULL,
	beneficiaries_tot float NULL,
	benefits_tot float NULL,
	BeneficiaryAge_avg varchar(255) NULL,
	BeneficiaryBenefit_avg float NULL,
	beneficiaries_ServiceRetirees float NULL,
	benefits_ServiceRetirees float NULL,
	ServiceRetireeAge_avg varchar(255) NULL,
	ServiceRetireeBenefit_avg decimal(18, 2) NULL,
	ServiceRetAge_avg varchar(255) NULL,
	ServiceRetTenure_avg varchar(255) NULL,
	benefits_DisabilityRetirees float NULL,
	beneficiaries_survivors float NULL,
	beneficiaries_SpousalSurvivors varchar(255) NULL,
	beneficiaries_other float NULL,
	DROPMembers float NULL,
	OtherMembers varchar(255) NULL,
	TotMembership float NULL,
	ActiveSalary_avg_est float NULL,
	BeneficiaryBenefit_avg_est float NULL,
	PVFB_InactiveNonVested decimal(18, 2) NULL,
	PVFB_active decimal(18, 2) NULL,
	PVFB_InactiveVested decimal(18, 2) NULL,
	PVFB_retiree float NULL,
	PVFB_other decimal(18, 2) NULL,
	PVFB_tot decimal(18, 2) NULL,
	PVFNC_tot decimal(18, 2) NULL,
	PVFNC_EE decimal(18, 2) NULL,
	PVFNC_ER decimal(18, 2) NULL,
	PVFS decimal(18, 2) NULL,
	MktAssets_ActRpt float NULL,
	ActAssets_AVA decimal(18, 2) NULL,
	ActLiabilities_EAN decimal(18, 2) NULL,
	ActLiabilities_PUC decimal(18, 2) NULL,
	TotFund_BnchmrkRtrn decimal(18, 2) NULL,
	EQTotal_Rtrn decimal(7, 5) NULL,
	EQTotal_Actl float NULL,
	EQTotal_Trgt decimal(7, 5) NULL,
	FITotal_Rtrn float NULL,
	FITotal_Actl float NULL,
	FITotal_Trgt decimal(7, 5) NULL,
	RETotal_Rtrn decimal(7, 5) NULL,
	RETotal_Actl float NULL,
	RETotal_Trgt decimal(7, 5) NULL,
	AltMiscTotal_Rtrn decimal(7, 5) NULL,
	AltMiscTotal_Actl float NULL,
	AltMiscTotal_Trgt decimal(7, 5) NULL,
	PETotal_Rtrn decimal(7, 5) NULL,
	PETotal_Actl float NULL,
	PETotal_Trgt decimal(7, 5) NULL,
	HFTotal_Rtrn decimal(7, 5) NULL,
	HFTotal_Actl float NULL,
	HFTotal_Trgt decimal(7, 5) NULL,
	COMDTotal_Rtrn decimal(7, 5) NULL,
	COMDTotal_Actl float NULL,
	COMDTotal_Trgt decimal(7, 5) NULL,
	CashTotal_Rtrn decimal(7, 5) NULL,
	CashTotal_Actl float NULL,
	Plan_masterID int NULL
)"""

RetirementSystemData_table = """CREATE TABLE RetirementSystemData(
	system_id float NULL,
	RetirementSystemName varchar(255) NULL,
	NumberofPlans varchar(255) NULL,
	NumberofEmployers varchar(255) NULL,
	fy float NULL,
	actives_tot float NULL,
	InactiveVestedMembers float NULL,
	InactiveNonVested float NULL,
	beneficiaries_tot float NULL,
	beneficiaries_ServiceRetirees float NULL,
	beneficiaries_survivors float NULL,
	beneficiaries_SpousalSurvivors float NULL,
	beneficiaries_other float NULL,
	DROPMembers float NULL,
	OtherMembers float NULL,
	TotMembership float NULL,
	BegMktAssets_net float NULL,
	contrib_EE_regular float NULL,
	contrib_ER_regular float NULL,
	contrib_ER_state float NULL,
	contrib_EE_PurchaseService float NULL,
	contrib_EE_other float NULL,
	contrib_ER_other float NULL,
	contrib_other float NULL,
	contrib_tot float NULL,
	FairValueChange_investments float NULL,
	FairValueChange_RealEstate float NULL,
	income_interest float NULL,
	income_dividends float NULL,
	income_InterestAndDividends float NULL,
	income_RealEstate float NULL,
	income_PrivateEquity float NULL,
	income_alternatives float NULL,
	income_international float NULL,
	income_OtherInvestments float NULL,
	expense_RealEstate float NULL,
	expense_PrivateEquity float NULL,
	expense_alternatives float NULL,
	expense_OtherInvestments float NULL,
	expense_investments float NULL,
	income_SecuritiesLending float NULL,
	expense_SecuritiesLending float NULL,
	income_SecuritiesLendingRebate float NULL,
	income_OtherAdditions float NULL,
	income_net float NULL,
	expense_TotBenefits float NULL,
	expense_RetBenefits float NULL,
	expense_DisabilityBenefits float NULL,
	expense_DeathBenefits float NULL,
	expense_DROPBenefits float NULL,
	expense_SurvivorBenefits float NULL,
	expense_COLABenefits float NULL,
	expense_LumpSumBenefits float NULL,
	expense_OtherBenefits float NULL,
	expense_refunds float NULL,
	expense_AdminExpenses float NULL,
	expense_Depreciation float NULL,
	expense_OtherDeductions float NULL,
	expense_net float NULL,
	adjustment_MktAssets float NULL,
	MktAssets_net float NULL,
	fund_id float NULL,
	RetirementSystemStateAbbrev varchar(255) NULL
)"""

RetirementSystemBasics_table = """CREATE TABLE RetirementSystemBasics(
	NumberOfPlans varchar(255) NOT NULL,
	ppd_system_directory_listed varchar(255) NOT NULL,
	RetirementSystemDesc varchar(850) NULL,
	RetirementSystemName varchar(255) NOT NULL,
	RetirementSystemStateAbbrev varchar(255) NOT NULL,
	system_id float NULL,
	sys_DataEndYear int NOT NULL,
	sys_DataStartYear int NOT NULL
)"""

StateLocalDisability_PPD_table = """CREATE TABLE StateLocalDisability_PPD(
	ppd_id int NULL,
	plan_name varchar(255) NULL,
	EEGroupID float NULL,
	EEGroupName varchar(255) NULL,
	EEGroupType float NULL,
	vesting float NULL,
	disability_scope varchar(255) NULL,
	disability_scope_notes varchar(255) NULL,
	dis_dur varchar(255) NULL,
	waiting_period float NULL,
	ind_eval varchar(255) NULL,
	reeval varchar(255) NULL,
	reeval_freq varchar(255) NULL,
	reeval_freq_notes varchar(255) NULL,
	ssdi_elig varchar(255) NULL,
	plan_after_ret_age varchar(255) NULL,
	formula_after_ret_age varchar(255) NULL,
	bene_fact float NULL,
	ten_for_bene_fact2 float NULL,
	bene_fact2 float NULL,
	ten_for_bene_fact3 float NULL,
	bene_fact3 float NULL,
	base_rr float NULL,
	assumed_age varchar(255) NULL,
	formula_type varchar(255) NULL,
	formula_type_notes varchar(255) NULL,
	years_for_FAS float NULL,
	reduction varchar(255) NULL,
	maximum_rr float NULL,
	minimum_rr float NULL,
	maximum_rr_desc varchar(255) NULL,
	minimum_rr_desc varchar(255) NULL,
	num_on_dis2018 float NULL,
	num_on_dis2017 float NULL,
	num_on_dis2016 float NULL,
	num_on_dis2015 float NULL,
	num_on_dis2014 float NULL,
	num_on_dis2013 float NULL,
	num_on_dis2012 float NULL,
	num_on_dis2011 float NULL,
	num_on_dis2010 float NULL,
	num_on_dis2009 float NULL,
	num_on_dis2008 float NULL,
	num_on_dis2007 float NULL,
	num_on_dis2006 float NULL,
	num_on_dis2005 float NULL,
	num_on_dis2004 float NULL,
	num_on_dis2003 float NULL,
	num_on_dis2002 float NULL,
	num_on_dis2001 float NULL,
	num_on_dis2000 float NULL
)"""

n = """RetirementSystemBasics"""

create_table_queries = [DCPlanData_table, RetirementSystemBasics_table, PensionTopStocksTopBonds_table, \
                         PensionInvestmentFees_table, PensionCreditRating_table, PPDDataLatest_table, \
                         PFPlan_PPDSupplement_table, RetirementSystemData_table, PensionInvestmentPerformanceDetailed_table, \
                         StateLocalDisability_PPD_table]


RetirementSystemBasics_table_drop = """DROP TABLE IF EXISTS RetirementSystemBasics"""

DCPlanData_table_drop = """DROP TABLE IF EXISTS DCPlanData"""

PensionTopStocksTopBonds_table_drop = """DROP TABLE IF EXISTS PensionTopStocksTopBonds"""

PensionInvestmentFees_table_drop = """DROP TABLE IF EXISTS PensionInvestmentFees"""

PensionCreditRating_table_drop = """DROP TABLE IF EXISTS PensionCreditRating"""

PPDDataLatest_table_drop = """DROP TABLE IF EXISTS PPDDataLatest"""

PFPlan_PPDSupplement_table_drop = """DROP TABLE IF EXISTS PFPlan_PPDSupplement"""

RetirementSystemData_table_drop = """DROP TABLE IF EXISTS RetirementSystemData"""

PensionInvestmentPerformanceDetailed_table_drop = """DROP TABLE IF EXISTS PensionInvestmentPerformanceDetailed"""

StateLocalDisability_PPD_table_drop = """DROP TABLE IF EXISTS StateLocalDisability_PPD"""

drop_table_queries = [DCPlanData_table_drop,  PensionTopStocksTopBonds_table_drop, PensionInvestmentFees_table_drop, \
                        PensionCreditRating_table_drop, PPDDataLatest_table_drop, PFPlan_PPDSupplement_table_drop, \
                        RetirementSystemData_table_drop, PensionInvestmentPerformanceDetailed_table_drop, \
                        StateLocalDisability_PPD_table_drop]

dcplandata_table_insert = """INSERT INTO public.dcplandata(
	dcplanid, state, planname, fy, year_est, ppd_id, planname_db, primary_, cashbalance, hybrid, mandatory_default, plantype, eligible_eegroups, actives, inactives, members_total, assets, investmentoptions, eq_avg, ee_contrate_mandatory, ee_contrate_max, ee_contrate_verbatim, er_contrate_matchrate, er_contrate_fixedrate, er_contrate_verbatim, conts_ee, conts_er, coveredpayroll)
	VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

pensioncreditrating_table_insert = """INSERT INTO public.pensioncreditrating(
	ppd_id, planname, fy, ratingagency, tot_mktvalue_sp, tot_parvalue_sp, tot_mktvalue_m, tot_parvalue_m, aaa_mktval_m, aaa_parval_m, aa_mktval_m, aa_parval_m, a_mktval_m, a_parval_m, baa_mktval_m, baa_parval_m, ba_mktval_m, ba_parval_m, b_mktval_m, b_parval_m, caaandbelow_mktval_m, caaandbelow_parval_m, unrated_mktval_m, unrated_parval_m, baandbelow_mktval_m, baandbelow_parval_m, agy_mktval_m, agy_parval_m, p1_mktval_m, p1_parval_m, p2_mktval_m, p2_parval_m, govgnteed_mktval_m, govgnteed_parval_m, aaa_govbond_mktval_m, aaa_govbond_parval_m, aa_govbond_mktval_m, aa_govbond_parval_m, a_govbond_mktval_m, a_govbond_parval_m, baa_govbond_mktval_m, baa_govbond_parval_m, ba_govbond_mktval_m, ba_govbond_parval_m, b_govbond_mktval_m, b_govbond_parval_m, caabelow_govbond_mktval_m, caabelow_govbond_parval_m, unrated_govbond_mktval_m, unrated_govbond_parval_m, aaa_agcmo_mktval_m, aaa_agcmo_parval_m, aaa_agdebent_mktval_m, aaa_agdebent_parval_m, aaa_agpool_mktval_m, aaa_agpool_parval_m, unrated_agpool_mktval_m, unrated_agpool_parval_m, aaa_cmo_mktval_m, aaa_cmo_parval_m, aa_cmo_mktval_m, aa_cmo_parval_m, a_cmo_mktval_m, a_cmo_parval_m, baa_cmo_mktval_m, baa_cmo_parval_m, ba_cmo_mktval_m, ba_cmo_parval_m, b_cmo_mktval_m, b_cmo_parval_m, caaandbelow_cmo_mktval_m, caaandbelow_cmo_parval_m, unrated_cmo_mktval_m, unrated_cmo_parval_m, aaa_corpcmo_mktval_m, aaa_corpcmo_parval_m, aa_corpcmo_mktval_m, aa_corpcmo_parval_m, a_corpcmo_mktval_m, a_corpcmo_parval_m, baa_corpcmo_mktval_m, baa_corpcmo_parval_m, ba_corpcmo_mktval_m, ba_corpcmo_parval_m, b_corpcmo_mktval_m, b_corpcmo_parval_m, candbelow_corpcmo_mktval_m, candbelow_corpcmo_parval_m, unrated_corpcmo_mktval_m, unrated_corpcmo_parval_m, aaa_convtbond_mktval_m, aaa_convtbond_parval_m, aa_convtbond_mktval_m, aa_convtbond_parval_m, a_convtbond_mktval_m, a_convtbond_parval_m, baa_convtbond_mktval_m, baa_convtbond_parval_m, ba_convtbond_mktval_m, ba_convtbond_parval_m, b_convtbond_mktval_m, b_convtbond_parval_m, caabelow_convtbond_mktval_m, caabelow_convtbond_parval_m, unrated_convtbond_mktval_m, unrated_convtbond_parval_m, aaa_corpbond_mktval_m, aaa_corpbond_parval_m, aa_corpbond_mktval_m, aa_corpbond_parval_m, a_corpbond_mktval_m, a_corpbond_parval_m, baa_corpbond_mktval_m, baa_corpbond_parval_m, ba_corpbond_mktval_m, ba_corpbond_parval_m, b_corpbond_mktval_m, b_corpbond_parval_m, caabelow_corpbond_mktval_m, caabelow_corpbond_parval_m, unrated_corpbond_mktval_m, unrated_corpbond_parval_m, aaa_highyield_mktval_m, aaa_highyield_parval_m, aa_highyield_mktval_m, aa_highyield_parval_m, a_highyield_mktval_m, a_highyield_parval_m, baa_highyield_mktval_m, baa_highyield_parval_m, ba_highyield_mktval_m, ba_highyield_parval_m, b_highyield_mktval_m, b_highyield_parval_m, caaandbelow_highyield_mktval_m, caaandbelow_highyield_parval_m, unrated_highyield_mktval_m, unrated_highyield_parval_m, aaa_emgmktdebt_mktval_m, aaa_emgmktdebt_parval_m, aa_emgmktdebt_mktval_m, aa_emgmktdebt_parval_m, a_emgmktdebt_mktval_m, a_emgmktdebt_parval_m, baa_emgmktdebt_mktval_m, baa_emgmktdebt_parval_m, ba_emgmktdebt_mktval_m, ba_emgmktdebt_parval_m, b_emgmktdebt_mktval_m, b_emgmktdebt_parval_m, caaandbelow_emgmktdebt_mktval_m, caaandbelow_emgmktdebt_parval_m, unrated_emgmktdebt_mktval_m, unrated_emgmktdebt_parval_m, aaa_nonusgov_mktval_m, aaa_nonusgov_parval_m, aa_nonusgov_mktval_m, aa_nonusgov_parval_m, a_nonusgov_mktval_m, a_nonusgov_parval_m, baa_nonusgov_mktval_m, baa_nonusgov_parval_m, ba_nonusgov_mktval_m, ba_nonusgov_parval_m, b_nonusgov_mktval_m, b_nonusgov_parval_m, caaandbelow_nonusgov_mktval_m, caaandbelow_nonusgov_parval_m, unrated_nonusgov_mktval_m, unrated_nonusgov_parval_m, aaa_glblcorpfix_mktval_m, aaa_glblcorpfix_parval_m, aa_glblcorpfix_mktval_m, aa_glblcorpfix_parval_m, a_glblcorpfix_mktval_m, a_glblcorpfix_parval_m, baa_glblcorpfix_mktval_m, baa_glblcorpfix_parval_m, ba_glblcorpfix_mktval_m, ba_glblcorpfix_parval_m, b_glblcorpfix_mktval_m, b_glblcorpfix_parval_m, caabelow_glblcorpfix_mktval_m, caabelow_glblcorpfix_parval_m, unrated_glblcorpfix_mktval_m, unrated_glblcorpfix_parval_m, a_coreplus_mktval_m, a_coreplus_parval_m, baa_commloan_mktval_m, baa_commloan_parval_m, ba_commloan_mktval_m, ba_commloan_parval_m, b_commloan_mktval_m, b_commloan_parval_m, caabelow_commloan_mktval_m, caabelow_commloan_parval_m, unrated_commloan_mktval_m, unrated_commloan_parval_m, aaa_seclendcol_mktval_m, aaa_seclendcol_parval_m, aa_seclendcol_mktval_m, aa_seclendcol_parval_m, a_seclendcol_mktval_m, a_seclendcol_parval_m, baa_seclendcol_mktval_m, baa_seclendcol_parval_m, ba_seclendcol_mktval_m, ba_seclendcol_parval_m, b_seclendcol_mktval_m, b_seclendcol_parval_m, caabelow_seclendcol_mktval_m, caabelow_seclendcol_parval_m, p1_seclend_mktval_m, p1_seclend_parval_m, p2_seclend_mktval_m, p2_seclend_parval_m, unrated_seclendcol_mktval_m, unrated_seclendcol_parval_m, aaa_cash_mktval_m, aaa_cash_parval_m, aa_cash_mktval_m, aa_cash_parval_m, a_cash_mktval_m, a_cash_parval_m, baa_cash_mktval_m, baa_cash_parval_m, govguaranteed_cash_mktval_m, govguaranteed_cash_parval_m, p1_cash_mktval_m, p1_cash_parval_m, unrated_cash_mktval_m, unrated_cash_parval_m, aaa_abs_mktval_m, aaa_abs_parval_m, aa_abs_mktval_m, aa_abs_parval_m, a_abs_mktval_m, a_abs_parval_m, baa_abs_mktval_m, baa_abs_parval_m, ba_abs_mktval_m, ba_abs_parval_m, b_abs_mktval_m, b_abs_parval_m, caaandbelow_abs_mktval_m, caaandbelow_abs_parval_m, unrated_abs_mktval_m, unrated_abs_parval_m, aaa_govag_mktval_m, aaa_govag_parval_m, aa_govag_mktval_m, aa_govag_parval_m, a_govag_mktval_m, a_govag_parval_m, baa_govag_mktval_m)
	VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

pensioninvestmentfees_table_insert = """INSERT INTO public.pensioninvestmentfees(
	ppd_id, planname, fy, notes_fees, nofeedata, group_fees, group_id, est_proportion, eqtotal_fee, fitotal_fee, retotal_fee, altmisctotal_fee, petotal_fee, hftotal_fee, comdtotal_fee, cashtotal_fee, othertotal_fee)
	VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

pensioninvestmentperformancedetailed_table_insert = """INSERT INTO public.pensioninvestmentperformancedetailed(
	ppd_id, planname, eegroupid, tierid, fy, eqdomesticmisc_rtrn, eqdomesticmisc_bnchmrkrtrn, eqdomesticmisc_bnchmrk, eqdomesticmisc_trgt, eqdomesticmisc_actl, eqdomesticlarge_rtrn, eqdomesticlarge_bnchmrkrtrn, eqdomesticlarge_bnchmrk, eqdomesticlarge_trgt, eqdomesticlarge_actl, eqdomesticmid_rtrn, eqdomesticmid_bnchmrkrtrn, eqdomesticmid_bnchmrk, eqdomesticmid_trgt, eqdomesticmid_actl, eqdomesticsmall_rtrn, eqdomesticsmall_bnchmrkrtrn, eqdomesticsmall_bnchmrk, eqdomesticsmall_trgt, eqdomesticsmall_actl, eqintlmisc_rtrn, eqintlmisc_bnchmrkrtrn, eqintlmisc_bnchmrk, eqintlmisc_trgt, eqintlmisc_actl, eqintldev_rtrn, eqintldev_bnchmrkrtrn, eqintldev_bnchmrk, eqintldev_trgt, eqintldev_actl, eqintlemerg_rtrn, eqintlemerg_bnchmrkrtrn, eqintlemerg_bnchmrk, eqintlemerg_trgt, eqintlemerg_actl, eqintlpass_rtrn, eqintlpass_bnchmrkrtrn, eqintlpass_bnchmrk, eqintlpass_trgt, eqintlpass_actl, eqintlactv_rtrn, eqintlactv_bnchmrkrtrn, eqintlactv_bnchmrk, eqintlactv_trgt, eqintlactv_actl, fidomestic_rtrn, fidomestic_bnchmrkrtrn, fidomestic_bnchmrk, fidomestic_trgt, fidomestic_actl, fiintl_rtrn, fiintl_bnchmrkrtrn, fiintl_bnchmrk, fiintl_trgt, fiintl_actl, cash_rtrn, cash_bnchmrkrtrn, cash_bnchmrk, cash_trgt, cash_actl, other_rtrn, other_bnchmrkrtrn, other_bnchmrk, other_trgt, other_actl, misceqfi_rtrn, misceqfi_bnchmrkrtrn, misceqfi_bnchmrk, misceqfi_trgt, misceqfi_actl, eqmisc_rtrn, eqmisc_bnchmrkrtrn, eqmisc_bnchmrk, eqmisc_trgt, eqmisc_actl, eqcore_rtrn, eqcore_bnchmrkrtrn, eqcore_bnchmrk, eqcore_trgt, eqcore_actl, eqlarge_rtrn, eqlarge_bnchmrkrtrn, eqlarge_bnchmrk, eqlarge_trgt, eqlarge_actl, eqmicro_rtrn, eqmicro_bnchmrkrtrn, eqmicro_bnchmrk, eqmicro_trgt, eqmicro_actl, eqopportunistic_rtrn, eqopportunistic_bnchmrkrtrn, eqopportunistic_bnchmrk, eqopportunistic_trgt, eqopportunistic_actl, eqsmall_rtrn, eqsmall_bnchmrkrtrn, eqsmall_bnchmrk, eqsmall_trgt, eqsmall_actl, eqsocialresp_rtrn, eqsocialresp_bnchmrkrtrn, eqsocialresp_bnchmrk, eqsocialresp_trgt, eqsocialresp_actl, eqseclend_rtrn, eqseclend_bnchmrkrtrn, eqseclend_bnchmrk, eqseclend_trgt, eqseclend_actl, eqglobal_rtrn, eqglobal_bnchmrkrtrn, eqglobal_bnchmrk, eqglobal_trgt, eqglobal_actl, eqglobalgrowth_rtrn, eqglobalgrowth_bnchmrkrtrn, eqglobalgrowth_bnchmrk, eqglobalgrowth_trgt, eqglobalgrowth_actl, fimisc_rtrn, fimisc_bnchmrkrtrn, fimisc_bnchmrk, fimisc_trgt, fimisc_actl, fibelowinvestgrd_rtrn, fibelowinvestgrd_bnchmrkrtrn, fibelowinvestgrd_bnchmrk, fibelowinvestgrd_trgt, fibelowinvestgrd_actl, ficash_rtrn, ficash_bnchmrkrtrn, ficash_bnchmrk, ficash_trgt, ficash_actl, ficonv_rtrn, ficonv_bnchmrkrtrn, ficonv_bnchmrk, ficonv_trgt, ficonv_actl, ficore_rtrn, ficore_bnchmrkrtrn, ficore_bnchmrk, ficore_trgt, ficore_actl, fieti_rtrn, fieti_bnchmrkrtrn, fieti_bnchmrk, fieti_trgt, fieti_actl, fiinvestgrd_rtrn, fiinvestgrd_bnchmrkrtrn, fiinvestgrd_bnchmrk, fiinvestgrd_trgt, fiinvestgrd_actl, filoans_rtrn, filoans_bnchmrkrtrn, filoans_bnchmrk, filoans_trgt, filoans_actl, fifundsfunds_rtrn, fifundsfunds_bnchmrkrtrn, fifundsfunds_bnchmrk, fifundsfunds_trgt, fifundsfunds_actl, finominal_rtrn, finominal_bnchmrkrtrn, finominal_bnchmrk, finominal_trgt, finominal_actl, finoncore_rtrn, finoncore_bnchmrkrtrn, finoncore_bnchmrk, finoncore_trgt, finoncore_actl, fistructured_rtrn, fistructured_bnchmrkrtrn, fistructured_bnchmrk, fistructured_trgt, fistructured_actl, fitips_rtrn, fitips_bnchmrkrtrn, fitips_bnchmrk, fitips_trgt, fitips_actl, fitreasury_rtrn, fitreasury_bnchmrkrtrn, fitreasury_bnchmrk, fitreasury_trgt, fitreasury_actl, ficorpbonds_rtrn, ficorpbonds_bnchmrkrtrn, ficorpbonds_bnchmrk, ficorpbonds_trgt, ficorpbonds_actl, fivalue_rtrn, fivalue_bnchmrkrtrn, fivalue_bnchmrk, fivalue_trgt, fivalue_actl, figlobal_rtrn, figlobal_bnchmrkrtrn, figlobal_bnchmrk, figlobal_trgt, figlobal_actl, fiemerg_rtrn, fiemerg_bnchmrkrtrn, fiemerg_bnchmrk, fiemerg_trgt, fiemerg_actl, fihighyield_rtrn, fihighyield_bnchmrkrtrn, fihighyield_bnchmrk, fihighyield_trgt, fihighyield_actl, fimortgage_rtrn, fimortgage_bnchmrkrtrn, fimortgage_bnchmrk, fimortgage_trgt, fimortgage_actl, fialt_rtrn, fialt_bnchmrkrtrn, fialt_bnchmrk, fialt_trgt, fialt_actl, fiopp_rtrn, fiopp_bnchmrkrtrn, fiopp_bnchmrk, fiopp_trgt, fiopp_actl, figips_rtrn, figips_bnchmrkrtrn, figips_bnchmrk, figips_trgt, figips_actl, altmisc_rtrn, altmisc_bnchmrkrtrn, altmisc_bnchmrk, altmisc_trgt, altmisc_actl, multiclass_rtrn, multiclass_bnchmrkrtrn, multiclass_bnchmrk, multiclass_trgt, multiclass_actl, eqprivate_rtrn, eqprivate_bnchmrkrtrn, eqprivate_bnchmrk, eqprivate_trgt, eqprivate_actl)
	VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

pensiontopstockstopbonds_table_insert = """INSERT INTO public.pensiontopstockstopbonds(
	ppd_id, planname, fy, est_proportion, stocklargest_share, stocklargestfive_share, stocklargestten_share, bondlargest_share, bondlargestfive_share, bondlargestten_share, stock1_name, stock1_ticker, stock1_dollars, stock2_name, stock2_ticker, stock2_dollars, stock3_name, stock3_ticker, stock3_dollars, stock4_name, stock4_ticker, stock4_dollars, stock5_name, stock5_ticker, stock5_dollars, stock6_name, stock6_ticker, stock6_dollars, stock7_name, stock7_ticker, stock7_dollars, stock8_name, stock8_ticker, stock8_dollars, stock9_name, stock9_ticker, stock9_dollars, stock10_name, stock10_ticker, stock10_dollars, bond1_name, bond1_dollars, bond1_couponrate, bond1_maturityyr, bond2_name, bond2_dollars, bond2_couponrate, bond2_maturityyr, bond3_name, bond3_dollars, bond3_couponrate, bond3_maturityyr, bond4_name, bond4_dollars, bond4_couponrate, bond4_maturityyr, bond5_name, bond5_dollars, bond5_couponrate, bond5_maturityyr, bond6_name, bond6_dollars, bond6_couponrate, bond6_maturityyr, bond7_name, bond7_dollars, bond7_couponrate, bond7_maturityyr, bond8_name, bond8_dollars, bond8_couponrate, bond8_maturityyr, bond9_name, bond9_dollars, bond9_couponrate, bond9_maturityyr, bond10_name, bond10_dollars, bond10_couponrate, bond10_maturityyr, bond_name)
	VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

pensiontopstockstopbonds_table_insert = """INSERT INTO public.pensiontopstockstopbonds(
	pf_id, stateabbrev, planname, fy, actassets_gasb, actliabilities_gasb, actfundedratio_gasb, uaal_gasb, actliabilities_other, payroll, requiredcontribution, percentreqcontpaid, arc, percentarcpaid, totalpensionliability, netposition, netpensionliability, adec, aec, coveredpayroll_gasb67, percentadec, actassets_est, actliabilities_est, actfundedratio_est, inflationassumption_gasb, investmentreturnassumption_gasb, actcostmeth_gasb, actcostmethcode_gasb, assetvalmeth_gasb, assetvalmethcode_gasb, assetsmoothingperiod_gasb, fundingmeth_gasb, fundingmethcode1_gasb, fundingmethcode2_gasb, uaalamortperiod_gasb, blendeddiscountrate, actives_tot, inactivevestedmembers, beneficiaries_tot, othermembers, totmembership, beneficiaryage_avg, serviceretireeage_avg, activeage_avg, activetenure_avg, activesalaries, activesalary_avg, benefits_tot, beneficiarybenefit_avg, benefits_serviceretirees, servicerettenure_avg, serviceretbenefit_avg, benefits_disabilityretirees, beneficiaries_survivors, contrib_ee_regular, contrib_er_regular, contrib_er_state, contrib_ee_purchaseservice, contrib_ee_other, contrib_er_other, contrib_other, contrib_tot, fairvaluechange_investments, fairvaluechange_realestate, income_interest, income_dividends, income_interestanddividends, income_realestate, income_privateequity, income_alternatives, income_international, income_otherinvestments, expense_realestate, expense_privateequity, expense_alternatives, expense_otherinvestments, expense_investments, income_securitieslending, expense_securitieslending, income_securitieslendingrebate, income_otheradditions, income_net, expense_totbenefits, expense_retbenefits, expense_disabilitybenefits, expense_deathbenefits, expense_dropbenefits, expense_survivorbenefits, expense_colabenefits, expense_lumpsumbenefits, expense_otherbenefits, expense_refunds, expense_adminexpenses, expense_depreciation, expense_otherdeductions, expense_net, adjustment_mktassets, mktassets_net, investmentreturn_1yr, investmentreturn_2yr, investmentreturn_3yr, investmentreturn_4yr, investmentreturn_5yr, investmentreturn_7yr, investmentreturn_8yr, investmentreturn_10yr, investmentreturn_12yr, investmentreturn_15yr, investmentreturn_20yr, investmentreturn_25yr, investmentreturn_30yr, investmentreturn_longterm, investmentreturn_ltstartyear, grossreturns, investmentreturn_1yr_est, investmentreturn_5yr_est, investmentreturn_10yr_est, contributionfy, normcostrate_tot, normcostrate_ee, normcostrate_er, reqcontrate_er, reqcontrate_tot, normcostamount_tot, normcostamount_ee, normcostamount_er, reqcontamount_er, reqcontamount_tot, normcostrate_tot_est, normcostrate_ee_est, normcostrate_er_est, reqcontrate_er_est, projectedpayroll)
	VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

pfplan_ppdsupplement_table_insert = """INSERT INTO public.pfplan_ppdsupplement(
	pf_id, stateabbrev, planname, fy, actassets_gasb, actliabilities_gasb, actfundedratio_gasb, uaal_gasb, actliabilities_other, payroll, requiredcontribution, percentreqcontpaid, arc, percentarcpaid, totalpensionliability, netposition, netpensionliability, adec, aec, coveredpayroll_gasb67, percentadec, actassets_est, actliabilities_est, actfundedratio_est, inflationassumption_gasb, investmentreturnassumption_gasb, actcostmeth_gasb, actcostmethcode_gasb, assetvalmeth_gasb, assetvalmethcode_gasb, assetsmoothingperiod_gasb, fundingmeth_gasb, fundingmethcode1_gasb, fundingmethcode2_gasb, uaalamortperiod_gasb, blendeddiscountrate, actives_tot, inactivevestedmembers, beneficiaries_tot, othermembers, totmembership, beneficiaryage_avg, serviceretireeage_avg, activeage_avg, activetenure_avg, activesalaries, activesalary_avg, benefits_tot, beneficiarybenefit_avg, benefits_serviceretirees, servicerettenure_avg, serviceretbenefit_avg, benefits_disabilityretirees, beneficiaries_survivors, contrib_ee_regular, contrib_er_regular, contrib_er_state, contrib_ee_purchaseservice, contrib_ee_other, contrib_er_other, contrib_other, contrib_tot, fairvaluechange_investments, fairvaluechange_realestate, income_interest, income_dividends, income_interestanddividends, income_realestate, income_privateequity, income_alternatives, income_international, income_otherinvestments, expense_realestate, expense_privateequity, expense_alternatives, expense_otherinvestments, expense_investments, income_securitieslending, expense_securitieslending, income_securitieslendingrebate, income_otheradditions, income_net, expense_totbenefits, expense_retbenefits, expense_disabilitybenefits, expense_deathbenefits, expense_dropbenefits, expense_survivorbenefits, expense_colabenefits, expense_lumpsumbenefits, expense_otherbenefits, expense_refunds, expense_adminexpenses, expense_depreciation, expense_otherdeductions, expense_net, adjustment_mktassets, mktassets_net, investmentreturn_1yr, investmentreturn_2yr, investmentreturn_3yr, investmentreturn_4yr, investmentreturn_5yr, investmentreturn_7yr, investmentreturn_8yr, investmentreturn_10yr, investmentreturn_12yr, investmentreturn_15yr, investmentreturn_20yr, investmentreturn_25yr, investmentreturn_30yr, investmentreturn_longterm, investmentreturn_ltstartyear, grossreturns, investmentreturn_1yr_est, investmentreturn_5yr_est, investmentreturn_10yr_est, contributionfy, normcostrate_tot, normcostrate_ee, normcostrate_er, reqcontrate_er, reqcontrate_tot, normcostamount_tot, normcostamount_ee, normcostamount_er, reqcontamount_er, reqcontamount_tot, normcostrate_tot_est, normcostrate_ee_est, normcostrate_er_est, reqcontrate_er_est, projectedpayroll)
	VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

ppddatalatest_table_insert = """INSERT INTO public.ppddatalatest(
	ppd_id, planname, fy, system_id, planfullname, source_planbasics, fiscalyeartype, planinceptionyear, planclosed, planyearclosed, administeringgovt, stateabbrev, statename, govtname, plantype, employeetypecovered, socseccovered, socseccovered_verbatim, coststructure, employertype, costsharing, benefitswebsite, eegroupid, tierid, actrptdate, fye, actcostmeth_gasb, assetvalmeth_gasb, fundingmeth_gasb, inflationassumption_gasb, investmentreturnassumption_gasb, actcostmethcode_gasb, assetvalmethcode_gasb, assetsmoothingperiod_gasb, fundingmethcode1_gasb, fundingmethcode2_gasb, uaalamortperiod_gasb, blendeddiscountrate, assetvalmeth, phasein, assetvalmeth_note, actcostmeth, actcostmeth_note, fundingmeth, fundingmeth_note, mktassets_smooth, actassets_smooth, netflows_smooth, assetvalmethcode, smoothingreset, gainlossconcept, gainlossbase_1, gainlossbase_2, gainloss, gainlossperiod, phaseinpercent, phaseinperiods, phaseintype, gainlossrecognition, assetsmoothingbaseline, expectedreturnmethod, addsubtractgainloss, uppercorridor, lowercorridor, actcostmethcode, fundmethcode_1, fundmethcode_2, payrollgrowthassumption, totamortperiod, remainingamortperiod, uaalyearestablished, wageinflation, actassets_gasb, actliabilities_gasb, actfundedratio_gasb, uaal_gasb, actliabilities_other, payroll, requiredcontribution, percentreqcontpaid, totalpensionliability, netposition, netpensionliability, actassets_est, actliabilities_est, actfundedratio_est, requiredcontribution_est, actfundedratio_gasb67, investmentconsultantname, investmentconsultantcode, investmentreturn_1yr, investmentreturn_2yr, investmentreturn_3yr, investmentreturn_4yr, investmentreturn_5yr, investmentreturn_7yr, investmentreturn_8yr, investmentreturn_10yr, investmentreturn_12yr, investmentreturn_15yr, investmentreturn_20yr, investmentreturn_25yr, investmentreturn_30yr, investmentreturn_longterm, investmentreturn_ltstartyear, grossreturns, georeturn_est, geogrowth_est, investmentreturn_1yr_est, investmentreturn_5yr_est, investmentreturn_10yr_est, avgreturn_3yr, avgreturn_5yr, avgreturn_10yr, expense_seclendmgmtfees, contrib_ee_regular, contrib_er_regular, contrib_er_state, contrib_ee_purchaseservice, contrib_ee_other, contrib_er_other, contrib_other, contrib_tot, fairvaluechange_investments, fairvaluechange_realestate, income_interest, income_dividends, income_interestanddividends, income_realestate, income_privateequity, income_alternatives, income_international, income_otherinvestments, expense_realestate, expense_privateequity, expense_alternatives, expense_otherinvestments, expense_investments, fvchange_seclend, income_securitieslending, expense_securitieslending, income_securitieslendingrebate, fvchange_seclend_ug, income_otheradditions, income_net, expense_totbenefits, expense_retbenefits, expense_disabilitybenefits, expense_deathbenefits, expense_dropbenefits, expense_survivorbenefits, expense_colabenefits, expense_lumpsumbenefits, expense_otherbenefits, expense_refunds, expense_adminexpenses, expense_depreciation, expense_otherdeductions, expense_net, adjustment_mktassets, mktassets_net, begmktassets_net, contrib_er_tot, contrib_other_tot, fairvaluechange_tot, income_interest_dividends_tot, expense_investments_tot, seclend_tot, investments_net, expense_other_tot, contributionfy, actuarialfirm, actuarialfirmcode, normcostrate_tot, normcostrate_ee, normcostrate_er, reqcontrate_er, reqcontrate_tot, normcostamount_tot, normcostamount_ee, normcostamount_er, reqcontamount_er, reqcontamount_tot, normcostrate_tot_est, normcostrate_ee_est, normcostrate_er_est, reqcontrate_er_est, projectedpayroll, uaalrate, beneficiaries_disabilityretirees, beneficiaries_dependentsurvivors, actives_tot, activesalaries, activeage_avg, activetenure_avg, activesalary_avg, inactivevestedmembers, inactivenonvested, beneficiaries_tot, benefits_tot, beneficiaryage_avg, beneficiarybenefit_avg, beneficiaries_serviceretirees, benefits_serviceretirees, serviceretireeage_avg, serviceretireebenefit_avg, serviceretage_avg, servicerettenure_avg, benefits_disabilityretirees, beneficiaries_survivors, beneficiaries_spousalsurvivors, beneficiaries_other, dropmembers, othermembers, totmembership, activesalary_avg_est, beneficiarybenefit_avg_est, pvfb_inactivenonvested, pvfb_active, pvfb_inactivevested, pvfb_retiree, pvfb_other, pvfb_tot, pvfnc_tot, pvfnc_ee, pvfnc_er, pvfs, mktassets_actrpt, actassets_ava, actliabilities_ean, actliabilities_puc, totfund_bnchmrkrtrn, eqtotal_rtrn, eqtotal_actl, eqtotal_trgt, fitotal_rtrn, fitotal_actl, fitotal_trgt, retotal_rtrn, retotal_actl, retotal_trgt, altmisctotal_rtrn, altmisctotal_actl, altmisctotal_trgt, petotal_rtrn, petotal_actl, petotal_trgt, hftotal_rtrn, hftotal_actl, hftotal_trgt, comdtotal_rtrn, comdtotal_actl, comdtotal_trgt, cashtotal_rtrn, cashtotal_actl, plan_masterid)
	VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

retirementsystemdata_table_insert = """INSERT INTO public.retirementsystemdata(
	system_id, retirementsystemname, numberofplans, numberofemployers, fy, actives_tot, inactivevestedmembers, inactivenonvested, beneficiaries_tot, beneficiaries_serviceretirees, beneficiaries_survivors, beneficiaries_spousalsurvivors, beneficiaries_other, dropmembers, othermembers, totmembership, begmktassets_net, contrib_ee_regular, contrib_er_regular, contrib_er_state, contrib_ee_purchaseservice, contrib_ee_other, contrib_er_other, contrib_other, contrib_tot, fairvaluechange_investments, fairvaluechange_realestate, income_interest, income_dividends, income_interestanddividends, income_realestate, income_privateequity, income_alternatives, income_international, income_otherinvestments, expense_realestate, expense_privateequity, expense_alternatives, expense_otherinvestments, expense_investments, income_securitieslending, expense_securitieslending, income_securitieslendingrebate, income_otheradditions, income_net, expense_totbenefits, expense_retbenefits, expense_disabilitybenefits, expense_deathbenefits, expense_dropbenefits, expense_survivorbenefits, expense_colabenefits, expense_lumpsumbenefits, expense_otherbenefits, expense_refunds, expense_adminexpenses, expense_depreciation, expense_otherdeductions, expense_net, adjustment_mktassets, mktassets_net, fund_id, retirementsystemstateabbrev)
	VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

statelocaldisability_ppd_table_insert = """INSERT INTO public.statelocaldisability_ppd(
	ppd_id, plan_name, eegroupid, eegroupname, eegrouptype, vesting, disability_scope, disability_scope_notes, dis_dur, waiting_period, ind_eval, reeval, reeval_freq, reeval_freq_notes, ssdi_elig, plan_after_ret_age, formula_after_ret_age, bene_fact, ten_for_bene_fact2, bene_fact2, ten_for_bene_fact3, bene_fact3, base_rr, assumed_age, formula_type, formula_type_notes, years_for_fas, reduction, maximum_rr, minimum_rr, maximum_rr_desc, minimum_rr_desc, num_on_dis2018, num_on_dis2017, num_on_dis2016, num_on_dis2015, num_on_dis2014, num_on_dis2013, num_on_dis2012, num_on_dis2011, num_on_dis2010, num_on_dis2009, num_on_dis2008, num_on_dis2007, num_on_dis2006, num_on_dis2005, num_on_dis2004, num_on_dis2003, num_on_dis2002, num_on_dis2001, num_on_dis2000)
	VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""
